/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Spritz Documentation",
  "tagline": "Decentralized social platform with AI agents, livestreaming, and Web3 messaging",
  "favicon": "icons/favicon-32x32.png",
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": true,
      "useCssCascadeLayers": true
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "url": "https://docs.spritz.chat",
  "baseUrl": "/",
  "organizationName": "Spritz-Labs",
  "projectName": "spritz-docs",
  "onBrokenLinks": "throw",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.ts",
          "editUrl": "https://github.com/Spritz-Labs/spritz-docs/tree/main/",
          "showLastUpdateAuthor": false,
          "showLastUpdateTime": false
        },
        "blog": {
          "showReadingTime": true,
          "feedOptions": {
            "type": [
              "rss",
              "atom"
            ],
            "xslt": true
          },
          "editUrl": "https://github.com/Spritz-Labs/spritz-docs/tree/main/",
          "onInlineTags": "warn",
          "onInlineAuthors": "warn",
          "onUntruncatedBlogPosts": "warn"
        },
        "theme": {
          "customCss": "./src/css/custom.css"
        },
        "sitemap": {
          "changefreq": "weekly",
          "priority": 0.5,
          "ignorePatterns": [
            "/tags/**",
            "/blog/tags/**",
            "/blog/authors/**",
            "/blog/archive",
            "/markdown-page"
          ],
          "filename": "sitemap.xml"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "og-image.png",
    "metadata": [
      {
        "name": "keywords",
        "content": "Spritz, decentralized social platform, Web3 messaging, AI agents, livestreaming, censorship resistant, open source, peer-to-peer, Waku protocol, x402 payments, Web3, blockchain, decentralized messaging, P2P communication, Livepeer, Huddle01, Sign-In with Ethereum, SIWE, Sign-In with Solana, SIWS, passkeys, crypto payments, decentralized social network"
      },
      {
        "name": "author",
        "content": "Spritz Labs"
      },
      {
        "name": "description",
        "content": "Complete documentation for Spritz - a decentralized social platform with Web3 messaging, AI agents, livestreaming, and peer-to-peer communication. Learn how to build censorship-resistant applications."
      },
      {
        "name": "robots",
        "content": "index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1"
      },
      {
        "name": "googlebot",
        "content": "index, follow"
      },
      {
        "property": "og:type",
        "content": "website"
      },
      {
        "property": "og:site_name",
        "content": "Spritz Documentation"
      },
      {
        "property": "og:title",
        "content": "Spritz Documentation - Decentralized Social Platform"
      },
      {
        "property": "og:description",
        "content": "Complete documentation for Spritz - a decentralized social platform with Web3 messaging, AI agents, livestreaming, and peer-to-peer communication."
      },
      {
        "property": "og:url",
        "content": "https://docs.spritz.chat"
      },
      {
        "property": "og:image",
        "content": "https://docs.spritz.chat/og-image.png"
      },
      {
        "property": "og:image:width",
        "content": "1200"
      },
      {
        "property": "og:image:height",
        "content": "630"
      },
      {
        "property": "og:image:alt",
        "content": "Spritz Documentation - Decentralized Social Platform"
      },
      {
        "property": "og:locale",
        "content": "en_US"
      },
      {
        "name": "twitter:card",
        "content": "summary_large_image"
      },
      {
        "name": "twitter:site",
        "content": "@SpritzLabs"
      },
      {
        "name": "twitter:creator",
        "content": "@SpritzLabs"
      },
      {
        "name": "twitter:title",
        "content": "Spritz Documentation - Decentralized Social Platform"
      },
      {
        "name": "twitter:description",
        "content": "Complete documentation for Spritz - a decentralized social platform with Web3 messaging, AI agents, livestreaming, and peer-to-peer communication."
      },
      {
        "name": "twitter:image",
        "content": "https://docs.spritz.chat/og-image.png"
      },
      {
        "name": "twitter:image:alt",
        "content": "Spritz Documentation - Decentralized Social Platform"
      },
      {
        "name": "application-name",
        "content": "Spritz Documentation"
      },
      {
        "name": "apple-mobile-web-app-title",
        "content": "Spritz Docs"
      },
      {
        "name": "theme-color",
        "content": "#FF5500"
      }
    ],
    "colorMode": {
      "respectPrefersColorScheme": true,
      "defaultMode": "light",
      "disableSwitch": false
    },
    "navbar": {
      "title": "Spritz",
      "logo": {
        "alt": "Spritz Logo",
        "src": "img/logo.svg",
        "srcDark": "img/logo.svg",
        "width": 32,
        "height": 32
      },
      "hideOnScroll": false,
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "docsSidebar",
          "position": "left",
          "label": "Docs"
        },
        {
          "type": "dropdown",
          "label": "AI Agents",
          "position": "left",
          "items": [
            {
              "type": "doc",
              "docId": "agents/intro",
              "label": "Overview"
            },
            {
              "type": "doc",
              "docId": "agents/rag-technical",
              "label": "RAG Technical"
            },
            {
              "type": "doc",
              "docId": "agents/mcp-servers",
              "label": "MCP Servers"
            },
            {
              "type": "doc",
              "docId": "agents/x402",
              "label": "x402 Payments"
            }
          ]
        },
        {
          "type": "dropdown",
          "label": "Livestreaming",
          "position": "left",
          "items": [
            {
              "type": "doc",
              "docId": "streaming/technical",
              "label": "Technical"
            }
          ]
        },
        {
          "type": "dropdown",
          "label": "Guides",
          "position": "left",
          "items": [
            {
              "type": "doc",
              "docId": "guides/messaging",
              "label": "Messaging"
            },
            {
              "type": "doc",
              "docId": "guides/video-calls",
              "label": "Video Calls"
            },
            {
              "type": "doc",
              "docId": "guides/groups",
              "label": "Groups"
            },
            {
              "type": "doc",
              "docId": "guides/channels",
              "label": "Channels"
            },
            {
              "type": "doc",
              "docId": "guides/friends",
              "label": "Friends"
            },
            {
              "type": "doc",
              "docId": "guides/calendar-scheduling",
              "label": "Calendar & Scheduling"
            },
            {
              "type": "doc",
              "docId": "guides/profile-settings",
              "label": "Profile Settings"
            },
            {
              "type": "doc",
              "docId": "guides/admin",
              "label": "Admin"
            }
          ]
        },
        {
          "type": "dropdown",
          "label": "API",
          "position": "left",
          "items": [
            {
              "type": "doc",
              "docId": "api/intro",
              "label": "Overview"
            },
            {
              "type": "doc",
              "docId": "api/complete",
              "label": "Complete Reference"
            },
            {
              "type": "doc",
              "docId": "api/agents-detailed",
              "label": "Agents API"
            },
            {
              "type": "doc",
              "docId": "api/streaming",
              "label": "Streaming API"
            }
          ]
        },
        {
          "to": "/blog",
          "label": "Blog",
          "position": "left"
        },
        {
          "href": "https://github.com/Spritz-Labs/spritz",
          "label": "GitHub",
          "position": "right"
        }
      ]
    },
    "footer": {
      "style": "light",
      "links": [
        {
          "title": "Documentation",
          "items": [
            {
              "label": "Getting Started",
              "to": "/docs/intro"
            },
            {
              "label": "AI Agents",
              "to": "/docs/agents/intro"
            },
            {
              "label": "Livestreaming",
              "to": "/docs/streaming/technical"
            },
            {
              "label": "API Reference",
              "to": "/docs/api/intro"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/Spritz-Labs/spritz"
            },
            {
              "label": "Issues",
              "href": "https://github.com/Spritz-Labs/spritz/issues"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "Blog",
              "to": "/blog"
            },
            {
              "label": "App",
              "href": "https://app.spritz.chat"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2026 Spritz Labs. Built with Docusaurus."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    }
  }
};
